#############################################################################################
#@author erik.flores 
#@fecha 13/NOVIEMBRE/2017
#############################################################################################
#RUTA-UBICACION DEL ARCHIVO DE CONFIGURACION DEL log4j2
LOG4J2.SUBDIRECTORY=/resources/log4j2.xml
#############################################################################################
#PARAMETROS MYSQL
DB.MYSQLDRIVER=com.mysql.jdbc.Driver
DB.URL=jdbc:mysql://srv00pcr03.atm.local:3306/CAMERAS
DB.MYSQLSERVER=srv00pcr03.atm.local
DB.MYSQLPORT=3306
DB.MYSQLDATABASE=CAMERAS
DB.PASSWD=ENC2:hKoomMMnASgTlrBctdIUyhALIeJc8eSixxAPyOdxCdgDN7i3BLi5zCuZBrORTdTwnACWXNoE+3Euh5k=
DB.USER=monitor.eventos
#############################################################################################
#SENTENCIA A EJECUTAR
SQL.Q1=select (@row_number:=@row_number + 1) AS item, grupo_camara, location_id, camara_serial, direccion, fecha_ultimo_evento, tiempo_transcurrido FROM ( select m.location_id as location_id, coalesce((select UPPER(gc.descripcion) from fotoradar_atm.grupo_camaras gc join fotoradar_atm.detalle_grupo_camaras dgc on dgc.id_grupo = gc.id where dgc.location_id = df.location_id and dgc.estado = 'A' ), 'METROVIA') AS grupo_camara, df.serial camara_serial, (select l.name from wd.locations as l where l.id = m.location_id ) direccion, (select l.geocode from wd.locations as l where l.id = m.location_id ) georeferencia, max(m.time) as fecha_ultimo_evento, TIME_TO_SEC(TIMEDIFF(now(), max(m.time))) as tiempo_transcurrido from cameras.messages as m left join fotoradar_atm.datos_fotoradar df on (df.location_id = m.location_id ) where m.time between DATE_SUB(NOW(), INTERVAL ? DAY) AND NOW() and m.location_id not in (888) group by location_id order by grupo_camara, location_id ) AS X, (select @row_number:=0) AS t where tiempo_transcurrido >= ? order by item  
SQL.Q2=
SQL.Q3=
SQL.Q4=
#INTERVALO DE TIEMPO PARA VERIFICACION DE EVENTOS (DIAS)
SQL.INTERVALO_DIAS=7
#INTERVALO DE TIEMPO PARA VERIFICACION DE EVENTOS (SEGUNDOS)
SQL.INTERVALO_TIEMPO=3600
#############################################################################################
#PASO POR PARAMETROS LAS FECHAS A PROCESAR. 
#CASO CONTRARIO SE ENVIAN EN BLANCO PARA QUE EL PROGRAMA CALCULE EL RANGO DE FECHAS
#QUE VA DESDE LA ULTIMA VEZ QUE SE REGISTR\u00d3 EN AXISATM.SCRTV_REVISIONES HASTA EL DIA ANTERIOR A LA FECHA ACTUAL
#FORMATO YYYY/MM/DD por ejemplo 2019-06-01
PARAM.FECHA_REPORTE=
PARAM.FECHA_INICIO=
PARAM.FECHA_FIN=
#############################################################################################
## TELEGRAM.CHATID=1136961221 ## TELEGRAM.GROUPCHATID=-4058484447 ## TELEGRAM.SUPERGROUPCHATID=-1002064421376
TELEGRAM.NOTIFICACION=Y
TELEGRAM.URL=https://api.telegram.org/bot%s/sendMessage?chat_id=%s&text=%s
TELEGRAM.TOKEN=ENC2:RHrI6ZYggNBp77C4UQO/p+EDc/0+22lRdLvO18+RVrnh8LV7m53d3TKZlrw/91Iq4gyR7eoNyqsdZJh8BUiOKZqReFfN4kspVLUCcQpeP4OJP4PyAfMQzIhs
TELEGRAM.CHATID=ENC2:U1Nf9V+CBpduz7It/NpfRzTRUstxlLvANAqQQ1WMP3gv+WbT26fiXaOxaMzsMk+fa8v/BJDH
#############################################################################################
#PARAMETROS NOTIFICACION POR CORREO
MAIL.NOTIFICACION=Y
MAIL.SERVER=act.atm.gob.ec
MAIL.PORT=587
MAIL.PASS=ENC2:KR88tgq7LOBKWkePqXffl7uwpsBecNF5llbpKF850Ju0JqLZverW9mGcQckb76kMxH73vTRY
MAIL.FROM=notificaciones.plavit@atm.gob.ec
MAIL.TO=erik.flores@atm.gob.ec;
MAIL.CC=
MAIL.BCC=
MAIL.SUBJECT=Resumen de camaras de fotoradar con un intervalo mayor a 1h sin transmitir eventos PLAVIT
MAIL.BODY=
#############################################################################################
